"""delete historical_data_type

Revision ID: 847a229f6a71
Revises: f20c30b8695c
Create Date: 2024-11-30 23:03:51.548403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '847a229f6a71'
down_revision: Union[str, None] = 'f20c30b8695c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_data_policy', 'historical_data_type')
    op.drop_column('historical_data_target', 'historical_data_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_data_target', sa.Column('historical_data_type', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('historical_data_policy', sa.Column('historical_data_type', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
