"""empty message

Revision ID: d4ef249b4529
Revises: beb67431e749
Create Date: 2024-12-01 00:13:21.041207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4ef249b4529'
down_revision: Union[str, None] = 'beb67431e749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_data_target_historical_data_id', table_name='historical_data_target')
    op.drop_table('historical_data_target')
    op.drop_index('ix_historical_data_policy_historical_data_id', table_name='historical_data_policy')
    op.drop_table('historical_data_policy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_data_policy',
    sa.Column('historical_data_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('policy_variable_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['policy_variable_id'], ['policy_variables.policy_variable_id'], name='historical_data_policy_ibfk_1'),
    sa.PrimaryKeyConstraint('historical_data_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_historical_data_policy_historical_data_id', 'historical_data_policy', ['historical_data_id'], unique=False)
    op.create_table('historical_data_target',
    sa.Column('historical_data_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_variable_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['target_variable_id'], ['target_variables.target_variable_id'], name='historical_data_target_ibfk_1'),
    sa.PrimaryKeyConstraint('historical_data_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_historical_data_target_historical_data_id', 'historical_data_target', ['historical_data_id'], unique=False)
    # ### end Alembic commands ###
