"""empty message

Revision ID: f20c30b8695c
Revises: 
Create Date: 2024-11-30 22:53:33.723906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20c30b8695c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_variables',
    sa.Column('policy_variable_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('policy_variable_id')
    )
    op.create_index(op.f('ix_policy_variables_name'), 'policy_variables', ['name'], unique=False)
    op.create_index(op.f('ix_policy_variables_policy_variable_id'), 'policy_variables', ['policy_variable_id'], unique=False)
    op.create_table('target_variables',
    sa.Column('target_variable_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('target_variable_id')
    )
    op.create_index(op.f('ix_target_variables_name'), 'target_variables', ['name'], unique=False)
    op.create_index(op.f('ix_target_variables_target_variable_id'), 'target_variables', ['target_variable_id'], unique=False)
    op.create_table('historical_data_policy',
    sa.Column('historical_data_id', sa.Integer(), nullable=False),
    sa.Column('policy_variable_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('historical_data_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['policy_variable_id'], ['policy_variables.policy_variable_id'], ),
    sa.PrimaryKeyConstraint('historical_data_id')
    )
    op.create_index(op.f('ix_historical_data_policy_historical_data_id'), 'historical_data_policy', ['historical_data_id'], unique=False)
    op.create_table('historical_data_target',
    sa.Column('historical_data_id', sa.Integer(), nullable=False),
    sa.Column('target_variable_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('historical_data_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['target_variable_id'], ['target_variables.target_variable_id'], ),
    sa.PrimaryKeyConstraint('historical_data_id')
    )
    op.create_index(op.f('ix_historical_data_target_historical_data_id'), 'historical_data_target', ['historical_data_id'], unique=False)
    op.create_table('simulation_request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('target_variable_id', sa.Integer(), nullable=True),
    sa.Column('policy_variable_id', sa.Integer(), nullable=True),
    sa.Column('request_forecast_years', sa.Integer(), nullable=True),
    sa.Column('proposed_policy_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['policy_variable_id'], ['policy_variables.policy_variable_id'], ),
    sa.ForeignKeyConstraint(['target_variable_id'], ['target_variables.target_variable_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_simulation_request_request_id'), 'simulation_request', ['request_id'], unique=False)
    op.create_table('forecast_data',
    sa.Column('forecast_data_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('forecast_year', sa.Integer(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('quantile_30', sa.Float(), nullable=True),
    sa.Column('quantile_70', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['simulation_request.request_id'], ),
    sa.PrimaryKeyConstraint('forecast_data_id')
    )
    op.create_index(op.f('ix_forecast_data_forecast_data_id'), 'forecast_data', ['forecast_data_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_data_forecast_data_id'), table_name='forecast_data')
    op.drop_table('forecast_data')
    op.drop_index(op.f('ix_simulation_request_request_id'), table_name='simulation_request')
    op.drop_table('simulation_request')
    op.drop_index(op.f('ix_historical_data_target_historical_data_id'), table_name='historical_data_target')
    op.drop_table('historical_data_target')
    op.drop_index(op.f('ix_historical_data_policy_historical_data_id'), table_name='historical_data_policy')
    op.drop_table('historical_data_policy')
    op.drop_index(op.f('ix_target_variables_target_variable_id'), table_name='target_variables')
    op.drop_index(op.f('ix_target_variables_name'), table_name='target_variables')
    op.drop_table('target_variables')
    op.drop_index(op.f('ix_policy_variables_policy_variable_id'), table_name='policy_variables')
    op.drop_index(op.f('ix_policy_variables_name'), table_name='policy_variables')
    op.drop_table('policy_variables')
    # ### end Alembic commands ###
